name: Hello World Workflow

on:
  pull_request:
    branches:
      - main]

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Echo Hello World
      run: echo "Hello, World"

